# Generated by Django 2.0.5 on 2018-11-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPanel',
            fields=[
                ('UserId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('IsActive', models.IntegerField()),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'UserPanel',
                'managed': False,
            },
        ),
    ]
