# Generated by Django 2.0.5 on 2018-12-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('DocumentItemId', models.AutoField(db_column='DocumentItemId', primary_key=True, serialize=False)),
                ('DocumentName', models.CharField(db_column='DocumentName', max_length=255)),
                ('Category', models.CharField(db_column='Category', max_length=10)),
                ('SortOrder', models.IntegerField(db_column='SortOrder')),
                ('EntryDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'DocumentItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageMaster',
            fields=[
                ('ImageId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=50)),
                ('CustomerCode', models.CharField(db_column='CustomerCode', max_length=50)),
                ('CaptureTimestamp', models.CharField(max_length=50)),
                ('FilePath', models.CharField(max_length=1200)),
                ('Created_DT', models.DateTimeField(auto_now_add=True)),
                ('Updated_DT', models.DateTimeField(auto_now_add=True)),
                ('Latitude', models.FloatField(default=34.75)),
                ('Longitude', models.FloatField(default=135.5)),
            ],
            options={
                'db_table': 'ImageMaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('InvoiceNo', models.CharField(db_column='InvoiceNo', max_length=11, primary_key=True, serialize=False)),
                ('InvoiceDate', models.CharField(db_column='InvoiceDate', max_length=30)),
                ('CustomerCode', models.CharField(db_column='CustomerCode', max_length=7)),
                ('CustomerName', models.CharField(db_column='CustomerName', max_length=50)),
                ('ContactPerson', models.CharField(db_column='ContactPerson', max_length=50)),
                ('Mobile', models.CharField(db_column='Mobile', max_length=100)),
                ('ChasisNo', models.CharField(db_column='ChasisNo', max_length=100)),
                ('EngineNo', models.CharField(db_column='EngineNo', max_length=100)),
            ],
            options={
                'db_table': 'vwInvoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationStatus',
            fields=[
                ('RegistrationStatusId', models.AutoField(db_column='RegistrationStatusId', primary_key=True, serialize=False)),
                ('InvoiceNo', models.CharField(db_column='InvoiceNo', max_length=25)),
                ('Status', models.CharField(db_column='Status', max_length=5)),
                ('EntryDate', models.DateTimeField()),
                ('EntryBy', models.CharField(db_column='EntryBy', max_length=25)),
            ],
            options={
                'db_table': 'RegistrationStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationType',
            fields=[
                ('RegisterTypeId', models.AutoField(db_column='RegisterTypeId', primary_key=True, serialize=False)),
                ('RegisterTypeName', models.CharField(db_column='RegisterTypeName', max_length=255)),
                ('EntryDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'RegistrationType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPanel',
            fields=[
                ('UserId', models.AutoField(db_column='UserId', primary_key=True, serialize=False)),
                ('UserInvoiceNo', models.CharField(db_column='UserInvoiceNo', max_length=255)),
                ('UserName', models.CharField(db_column='UserName', max_length=255)),
                ('Password', models.CharField(db_column='Password', max_length=255)),
                ('Status', models.IntegerField(db_column='Status')),
                ('EntryDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'UserPanel',
                'managed': False,
            },
        ),
    ]
